version: "3.8"

services:
  yt-service:
    build: .
    container_name: youtube-analysis-service
    ports:
      - "8080:8080"
    environment:
      - PUPPETEER_SKIP_DOWNLOAD=false
    restart: unless-stopped
